name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Auth Service
        run: |
          cd auth-service
          ./mvnw clean package -DskipTests

      - name: Build Resume Service
        run: |
          cd resume-service
          ./mvnw clean package -DskipTests

      - name: Build API Gateway
        run: |
          cd api-gateway
          ./mvnw clean package -DskipTests

  ai-service-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install AI Service Dependencies
        run: |
          cd ai-service
          pip install -r requirements.txt

  docker-build:
    runs-on: ubuntu-latest
    needs:
      - frontend-build
      - backend-build
      - ai-service-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Containers
        run: docker compose build